/*
 * main.h
 *
 * Created: 12/14/2018 9:30:35 PM
 *  Author: z
 */ 

#define PC_ONLY

#ifndef MAIN_H_
#define MAIN_H_

#define MAXSTRLENGTH 50

enum TokenType { MUL, MINUS, MOD, PLUS, DIV,
LSHIFT, RSHIFT, AND, OR,
XOR, IF, ELSE, THEN, ID ,
NOT, GT, LT, LTE, GTE, EQ, AS,
NEQ, TRUE, FALSE, NEWLINE, RETURN,
STR_CONCAT, COMMA, COLON, INCR, DECR, POW,
INTDIV, LPAREN, RPAREN, END, INT, STR, BOOL,
END_IF, WHILE, WEND, SUB, DIM, LET,
END_FUNCTION, FUNC_CALL, FUNCTION_DECLARE,
FOR, TO, STEP, NEXT, GOSUB, LABEL, FLOATNUM };


#endif /* MAIN_H_ */